
localizedData.ru = {
  name: 'Строганов Никита',
  about: '',
  profession: 'frontend deverloper',
  location: 'Россия, Санкт-Петербург',
  projects: [{
    title: 'Duel game',
    link: '#',
    description: '',
  },
  ],
  works: [{
    dateStart: 2017,
    dateEnd: 2015,
    title: 'Freelance',
    subtitle: 'Lorem ipsum dolor',
    description: 'php symfony twig',
  }],
  educations: [{
    dateStart: 2017,
    dateEnd: 2018,
    title: 'Обучение с наставником',
    subtitle: 'vue.js, node.js, mongodb',
    description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod eaque excepturi.',
  },
  {
    dateStart: 2015,
    dateEnd: 2010,
    title: '<strong>Государственный университет аэрокосмического приборостроения</strong>',
    subtitle: 'Программирование в компьютерных системах',
    description: '',
  },
  ],
  personalSkills: [
    '1',
    '2',
    '3',
    '4',
  ],
  hobbies: [
    'любительский хоккей,',
    'фристайл на роликах,',
    'программирование микроконтроллеров,',
    'туризм.',
  ],
  i: {
    about: 'немного обо мне',
    email: 'Эл. почта',
    hobbies: 'Увлечения',
    info: 'Профиль',
    links: 'Ссылки',
    location: 'Адресс',
    name: 'Имя',
    personalSkills: 'Личные качества',
    age: 'Возраст',
    professionalSkills: 'Профессиональные навыки',
    sections: {
      work: 'Опыт работы',
      education: 'Образование',
      projects: 'Проекты',
    },
  },
};
